# ============================================================
# Configuration du projet
# ============================================================
spring.application.name=parc-informatique
server.port=8080


# ============================================================
# MySQL
# ============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/parc_informatique_db?useSSL=false&serverTimezone=Africa/Tunis&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Mysql123a

# Driver JDBC utilise pour communiquer avec MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ============================================================
# JPA - Creation automatique des tables
# ============================================================

# Hibernate met a jour automatiquement les tables.
spring.jpa.hibernate.ddl-auto=update

# Affiche les requetes SQL dans la console.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Indique a Hibernate qu'il travaille avec MySQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ============================================================
# Upload PDF chartes
# ============================================================

# Activation de l'upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Les fichiers seront enregistres dans le dossier "uploads/chartes" a la racine du projet
app.upload.dir=uploads/chartes


# ============================================================
# JWT - Utilise pour l'authentification
# ============================================================

# Sert a : Generer les tokens / Verifier les tokens
app.jwt.secret=TunisieCablesOneTechSecretKey2024SuperLongKeyForSecurity

# Duree de validite du token en millisecondes (ici 1 jour)
app.jwt.expiration=86400000


# ============================================================
# Logging
# ============================================================
logging.level.com.tunisiecables=DEBUG
logging.level.org.springframework.security=INFO